spring:
  profiles:
    active: producer
# Producer


spring:
  profiles: producer
  kafka:
    properties:
      bootstrap:
        servers: localhost:9092

      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        acks: all
        retries: 3
        batch-size: 16384
        linger-ms: 1
        buffer-memory: 33554432
server:
  port: 8081

# Consumer
server:
  port: 8082
spring:
  profiles: consumer
  kafka:
    properties:
      bootstrap:
        servers: localhost:9092
      consumer:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        group-id: my-group
        auto-offset-reset: earliest
        enable-auto-commit: true
        auto-commit-interval: 1000ms
        max-poll-records: 50
