# practical
---
spring:
  config:
    activate:
      on-profile: accountProducer
  kafka:
    properties:
      bootstrap:
        servers: localhost:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        acks: all
        retries: 3
        batch-size: 16384
        buffer-memory: 33554432
        linger-ms: 0
        queue-buffering-max-ms: 0
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: notificationConsumer
  kafka:
    properties:
      bootstrap:
        servers: localhost:9092
      consumer:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        group-id: notificationGroupId
        auto-offset-reset: earliest
        enable-auto-commit: true
        auto-commit-interval: 1000ms
        max-poll-records: 50
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: statisticConsumer
  kafka:
    properties:
      bootstrap:
        servers: localhost:9092
      consumer:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        group-id: statisticGroupId
        auto-offset-reset: earliest
        enable-auto-commit: true
        auto-commit-interval: 1000ms
        max-poll-records: 50
server:
  port: 8082


# example
---
spring:
  config:
    activate:
      on-profile: producer
  kafka:
    properties:
      bootstrap:
        servers: localhost:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        acks: all
        retries: 3
        batch-size: 16384
        buffer-memory: 33554432
        linger-ms: 0
        queue-buffering-max-ms: 0
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: groupA
  kafka:
    properties:
      bootstrap:
        servers: localhost:9092
      consumer:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        group-id: group-a
        auto-offset-reset: earliest
        enable-auto-commit: true
        auto-commit-interval: 1000ms
        max-poll-records: 50
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: groupB
  kafka:
    properties:
      bootstrap:
        servers: localhost:9092
      consumer:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        group-id: group-b
        auto-offset-reset: earliest
        enable-auto-commit: true
        auto-commit-interval: 1000ms
        max-poll-records: 50
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: groupC
  kafka:
    properties:
      bootstrap:
        servers: localhost:9092
      consumer:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        group-id: group-c
        auto-offset-reset: earliest
        enable-auto-commit: true
        auto-commit-interval: 1000ms
        max-poll-records: 50
server:
  port: 8083
